apiVersion: v1
kind: Secret
metadata:
  name: neondb-secret
type: Opaque
stringData:
  database-url: "postgresql://neondb_owner:npg_oxZVKi8LqYn3@ep-falling-field-a11hhwcs-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
