apiVersion: v1
kind: Secret
metadata:
  name: neondb-secret
type: Opaque
stringData:
  # Paste your full Neon DB connection string here
  # Format: postgresql://user:password@ep-xxxx.region.aws.neon.tech/dbname?sslmode=require
  database-url: "postgresql://YOUR_NEON_USER:YOUR_NEON_PASSWORD@ep-xxxx-xxxx.region.aws.neon.tech/YOUR_DB_NAME?sslmode=require"
